# Generated by Django 2.1.2 on 2018-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('phone_system', models.SmallIntegerField(choices=[(0, 'AndroidPhone'), (1, 'iOSPhone'), (2, 'AndroidPad'), (3, 'iOSPad')], verbose_name='手机系统')),
                ('result', models.SmallIntegerField(choices=[(0, 'watting'), (1, 'success'), (2, 'fail')], default=0, verbose_name='测试结果')),
            ],
            options={
                'verbose_name': '测试用例实例',
                'verbose_name_plural': '测试用例实例',
                'db_table': 'ps_testcase',
            },
        ),
        migrations.CreateModel(
            name='TestCaseBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('description', models.TextField(max_length=200)),
                ('level', models.IntegerField()),
                ('test_man', models.TextField(max_length=50)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCase')),
            ],
            options={
                'verbose_name': '测试用例实例Bug',
                'verbose_name_plural': '测试用例实例Bug',
                'db_table': 'ps_testcase_bug',
            },
        ),
        migrations.CreateModel(
            name='TestCaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': '测试用例文档',
                'verbose_name_plural': '测试用例文档',
                'db_table': 'ps_testcase_document',
            },
        ),
        migrations.CreateModel(
            name='TestCaseFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.CharField(max_length=200)),
                ('doucument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCaseDocument')),
            ],
            options={
                'verbose_name': '测试用例功能模块',
                'verbose_name_plural': '测试用例功能模块',
                'db_table': 'ps_testcase_function',
            },
        ),
        migrations.CreateModel(
            name='TestCaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='portrait', verbose_name='用例图片')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCase')),
                ('test_case_bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCaseBug')),
            ],
            options={
                'verbose_name': '测试用例实例Bug',
                'verbose_name_plural': '测试用例实例Bug',
                'db_table': 'ps_testcase_img',
            },
        ),
        migrations.CreateModel(
            name='TestCaseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('expection', models.CharField(max_length=300)),
                ('remarks', models.CharField(max_length=300)),
                ('doucument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCaseDocument')),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCaseFunction')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'ps_testcase_module',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('logo', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'null'), (106, '东方香港'), (101, '银河')], default=0, verbose_name='券商类别')),
            ],
            options={
                'verbose_name': '测试用例实例Bug',
                'verbose_name_plural': '测试用例实例Bug',
                'db_table': 'ps_trader',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCaseModule'),
        ),
    ]
