# Generated by Django 2.1.2 on 2018-11-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='broker',
            field=models.IntegerField(choices=[(0, 'null'), (106, '东方香港'), (101, '银河')], default=0, verbose_name='券商'),
        ),
    ]
