# Generated by Django 2.1.2 on 2018-11-14 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.Trader', verbose_name='券商'),
        ),
    ]
