# Generated by Django 2.1.2 on 2018-11-14 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=200)),
                ('trader_code', models.CharField(max_length=20)),
                ('commit_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('isdebug', models.BooleanField()),
                ('server_ip', models.CharField(max_length=100)),
                ('svn_version', models.CharField(max_length=20)),
                ('update_address', models.CharField(max_length=100)),
                ('version_code', models.CharField(max_length=20)),
                ('upadete_version', models.CharField(max_length=200)),
                ('bundle_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '开发版本说明书',
                'verbose_name_plural': '开发版本说明书',
                'db_table': 'ps_version_info',
            },
        ),
        migrations.CreateModel(
            name='VersionInfoBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.TextField(max_length=200)),
                ('level', models.IntegerField()),
                ('solution', models.TextField(max_length=200)),
                ('result', models.TextField(max_length=50)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('versioninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versioninfo.VersionInfo')),
            ],
            options={
                'verbose_name': '开发版本说明书bug',
                'verbose_name_plural': '开发版本说明书bug',
                'db_table': 'ps_version_bug',
            },
        ),
    ]
